apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: project-secret
  namespace: project-namespace
spec:
  encryptedData:
    DISCORD_URL: AgAzREwuTDP0YFc+oKejAIW6EEtBFCaxkFXaBff3DZ6DlYvSG1SKf7/dAMYtWocROOps6wyjO2dFpfEXa4BII8J1J5/rdMbvIXLOyYLFC6FWR5bzyPd1Au6Sjxy9SS8QilJfjlJDONAS3q77QXQ4sqnn8WfjqPnbud2Vj6Ta+SpgWfjWwSEf6Q1l2clUwcTbRt+6U8pCCQB2uM3CPgWnOzyvKzbAaQegIEc8hnSKRbi8Vuh1iZgDTjNo3xkMrdczA6VA9Qh80lgncaBcIE513cy+p7wh+u36cr/0l4uktAVbxPQxwArdoYKmGnZzlu3DYEwZVS+cu4BmphR24dHx7iNykW8zUI3hmVtZObewsXQEEcKCUh/drlmfvTqbKbE0Urc7vE3cValGV1yeUn4iZqjHllXlDRv01tYJ9IcqPgBi/sixOMREhf4gdeoEjAg/Z1BgRCcGxD2O19woiAlUINIsHGuuA0QHJVwm1psoDBhBbdsR9SHIxek+UXUFeWZ89jyc1W5/pXuKy4WJ+8QQlpGnLYJsyB98VxFMXSPZtwC5vma3vjpzvyCubCAFzIV9CI5Ue4ecRBwkVng7dJs2GCnan8sTK69RO8v4Jzae3UiTv79dBIejf3IBlMamI8tn7cAk5nuL393J8PAml+dlNdkGmdAiDZBZbEVzgRvtaIJCoeZ+Tv4T5QRME09o/pVqfAtbUZryfAbMoZ+kthEAmmP1JntyACC/A/C5SPk13j01obnZH0izK0v05kE+VYv9Dkju7GxMw5vLQRRu+3Q2kd4+OmcQzOv+hPfG9NTS99T3W5ytjUKh26i8/m177ZWn6moObzzjKihZ0tEUMZxxQzKyN8TEOMwWdxI=
    POSTGRES_PASSWORD: AgAe+FNb+8lrZtkOciayXat4sCTkdoyH20+ScdaMusvDzkYRBcFeMvqR5FjkTtaFb3RoKDqLbGLO9h0RzUKRxxGViQ/UVJ5S2jMjWlLzD4gzokf8TUhKioMmA6E7oyBvvzYe3o/WAf3hRCoJOom5VwyXlYf5WAwPCrIOawGvEZEN6TsRR4PEbS4WX1izjdvGOfNdAY5qrvg4HwoeJi4qId++ItX5eKQdOFCD3Rp1x9HcyC30KLK2mVZHFXABUA3LGgGyUdMne9zbmkctz5t2ZUSY34nrHhZ9/j0zogK+xBXW3584LyqdboROGbLAy+uLVcEoyQkHYvBYoNwhkw5Ld+BgrqD1cDMRDoZ1XLk34rHpQensU8D0x5h3CgkhOkxk95Nwz2dmDOP6gLewNq6mtwZ49fe7lYbcWUoyKRCCX+jF3U1V+J78wrZCww+6dCYKQK8c2qXQxWEEpMXKGDBf6qmVbfnZ4/r60ya8ZxxfXC2n/rYO3Tk5hQEv3r1xkm3mhvuQHlhw+i6IAyf9FuFDA2Hbr8fmTLH71iLtkwem3YgLfEemd5Vd74QSsY7s+wzhgV8hUJQ8HkiZ6wBl5fxYhOAjF0Be7DhJgr4UTMRMo3S8y1eGh39cM3aH5sUEAZY9SDiMm4UWaR5hAi/GD1OG5jk4y5lwVVE281mKzQPPuQ0BYTnG1794G/+udiUCE1A9EiOd8cMk
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: project-secret
      namespace: project-namespace

