apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: main-knative
  namespace: main-namespace
spec:
  template:
    metadata:
      name: main-knative-svc-v1
    spec:
      containers:
        - image: robsondepaula/pingpong:4_01
          envFrom:
            - secretRef:
                name: db-password
          env:
            - name: SVC_PORT
              valueFrom:
                configMapKeyRef:
                  name: main-svc-config
                  key: SVC_PORT
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: main-svc-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: main-svc-config
                  key: POSTGRES_PORT
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: main-svc-config
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: main-svc-config
                  key: POSTGRES_DB
            - name: POSTGRES_TABLE
              valueFrom:
                configMapKeyRef:
                  name: main-svc-config
                  key: POSTGRES_TABLE