apiVersion: v1
kind: Service
metadata:
  name: back-svc
  namespace: project-namespace
spec:
  type: ClusterIP
  selector:
    app: project-svc
  ports:
    - name: http
      protocol: TCP
      port: 2346
      targetPort: 3001