apiVersion: v1
kind: Service
metadata:
  name: main-svc
  namespace: main-namespace
spec:
  type: NodePort
  selector:
    app: main-app
  ports:
    - name: http
      port: 2345
      protocol: TCP
      targetPort: 3000