apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: main-hpa
  namespace: main-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: main-dep
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50