apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: project-app-hpa
  namespace: project-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: project-app-dep
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50