apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
  - service-back.yaml
  - service-front.yaml
  - deployment-back.yaml
  - deployment-front.yaml
  - hpa-front.yaml
  - hpa-back.yaml
images:
  - name: BACKEND_IMAGE
    newName: robsondepaula/project-service:3_03
  - name: FRONTEND_IMAGE
    newName: robsondepaula/project:3_03
