apiVersion: v1
kind: Service
metadata:
  name: project-svc
spec:
  type: NodePort
  selector:
    app: project-app
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 80
      targetPort: 80