apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-password
  namespace: project-namespace
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCx5celnMWqd4U8L8acKZUF1fioLBGYzYbNwOKPOsw4BQqLnkCVwhpxivBhHEPpiBS5jwGbpWId9S0Kb2rWo4C3PwmcYbACDfL7+X/69z03dDyuc8ucPT0mc+xtkjE81mWUn8AHXgIktC6XLyVwSFJGq2GNbNwCpLA3Z5P0JUQzjm2qCZ7k+Tl6h5nIugujBK9vHVDZmByVwQTmX8M26+F1iMAi+ZIoY6pDrWBZGqgdFiCS32IPEgjFj7QFvJmciW9+Ic3qRhQcQG/jXPPfXUn/rX/C+1S2mOiINuTDdbiEmuS6NMCxeMNH2CcyENx+RoyAw2DESV7PTD0HFJYiaGp/NP0qmq/XJN3Lct/X9gvQK291CgfuIG534T7atkUaRXKSLjLwt1WKp4loXFxZ+dfqLcCa6C6tXQlW9CdiFJVBGwQAXZDWv8YAzdpt8Y1CTHkWpffeazPeq/HKJ9RHhCufn9+o3sPYWECTLKd4Dz7Zw2RDkdOaOYBzml/IxWn08d1p/Ea1cWbDomUMPsYQD0uKb2jfSc1yNGDwqCmBJTXEi38ZlhyBjpC1KEjxpMKyXLL3UMHj9NBwN521yhqN/aVXgvgI6cRWeo+pjseAfA3NSxFLskExfILqmzoeljX7fw09G1bmOK69fvjIlgE9yWaAdMvmb4WMxR+1q21qLEhry2TdcjSM8bYH/8WqSkPyvMFZuuut
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: db-password
      namespace: project-namespace

