apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: daily-url
  namespace: project-namespace
spec:
  schedule: "0 6 * * *" # every day at 06:00
  #schedule: "*/1 * * * *" # testing, every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-container
            image: robsondepaula/cron-job-todo:2_09
            imagePullPolicy: Always
            env:
            - name: TODO_ENDPOINT
              value: back-svc.project-namespace.svc.cluster.local:2346
          restartPolicy: Never