apiVersion: v1
kind: Service
metadata:
  name: project-app
spec:
  type: NodePort
  selector:
    app: project-app
  ports:
    - name: front-http-port
      port: 2345
      targetPort: 80 # react app served by nginx