apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-site-controller-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-site-controller
  template:
    metadata:
      labels:
        app: dummy-site-controller
    spec:
      serviceAccountName: dummy-site-controller-account
      containers:
        - name: dummy-site-controller
          image: robsondepaula/dwk-dummy-site:5_01
