apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - persistentvolumeclaim.yaml
  - ingress.yaml
  - service-back.yaml
  - service-front.yaml
  - deployment-back.yaml
  - deployment-front.yaml
images:
  - name: BACKEND_IMAGE
    newName: robsondepaula/project-service:2_10
  - name: FRONTEND_IMAGE
    newName: robsondepaula/project:2_08
