apiVersion: v1
kind: Service
metadata:
  name: project-svc
  namespace: project-namespace
spec:
  type: NodePort
  selector:
    app: project-svc
  ports:
    - name: http
      protocol: TCP
      port: 2346
      targetPort: 3001