apiVersion: v1
kind: Service
metadata:
  name: project-svc
spec:
  type: ClusterIP
  selector:
    app: project-app
  ports:
    - name: http
      protocol: TCP
      port: 2345
      targetPort: 80 # react app served by nginx
    - name: serviceport
      port: 2346
      protocol: TCP
      targetPort: 3001