apiVersion: v1
kind: Service
metadata:
  name: main-app
  namespace: main-namespace
spec:
  type: ClusterIP
  selector:
    app: main-app
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3001