apiVersion: v1
kind: ConfigMap
metadata:
  name: project-svc-config
data:
  SVC_PORT: "3001"
  POSTGRES_PORT: "35432"
  POSTGRES_USER: "user"
  POSTGRES_DB: "project_db"
  POSTGRES_TABLE: "project_table"
