apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-password
  namespace: project-namespace
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAQ+13aXeXMeP17qnUfORVOdQ/QDOzKpDHWhra8xVmJCMrXW5QdbAXgnzaTrajXgPu0av/0Y1TZgRWBKcOfOR/F8m3BNBLpL58PlQu3LrKtt3QHotMTB7ckun7rmsIt0Oys4SAi6jNCluonUwDNSOkTa4ui1qU8mInJwM6VwLwGoRlqEbE5DeQYWu7V5Dm5h0BYYJEZAx1jfpib4VBAA8slgsSfCaArHMQooNKIkcbw72FzSRsJ6nExAw9x7dRsMoGyCOW2OWdKgplVlnjhRWdZ4eBDEbM6xgXfY7sUMuVqeaGa9n6ltSpYj03efjMaN21wbUvknCYev3GWhJeR9frWcY9PYa88PfP6XhUwXF3WLphB2fAROM1abN1iIM2SUfld+0aSHZ1qvi0gIYUw1fpPpi6qbVwZcbLqQPKUf922RBCwl7rC4km9xmWAwbo/tXOCX/chcAz333oDCdfKu4IDCwcDjkp7N6HnSYzhcm6yLns0bjX840V/gl+1orc2jMdTW6N6S6tMPnmhPhVD5+5/e5Ey+6zSGqhspjIenzSXuCun0s7BjrWH6elQw6By1eRYQiFBC5u2wT+524mAGA5N2XxBd4tyfjywdfmEhiSXU91SUCouylNzI6Ayhhz5sxakrYgFjBBUHY1/dDOT1zoBFuyOk8uajHFmccCYBMpyAK71mM/nr4T3gvNa52Q6lPHFsukf
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: db-password
      namespace: project-namespace

