apiVersion: ENC[AES256_GCM,data:Gl0=,iv:NL1ScYok42zwEsydtuNqvtmWsE2qiX7Om8L9u9mxgJU=,tag:VFQtLBoyvCI4QHl4YRkG1Q==,type:str]
kind: ENC[AES256_GCM,data:XZ+H9NKZ,iv:bs2VlLWr4H3qELNnEWcSKXV1kjpai87TXonx/Lfe91M=,tag:z70LIHIXnxazefzF5AK0Vw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UsVC2EvbiK73ol8=,iv:WioPeZEnmtBdC7eVttg1gkpsXcf2Vr7G5RGs6QufTik=,tag:/pV1e9TIr35+WVyqq2RMhw==,type:str]
    namespace: ENC[AES256_GCM,data:VmBgLBgVqagkofwpDQO3i28=,iv:XgmGONFnl8PpBE6T5JOIrcNri+a2G+WnUE/HY7A/s1Q=,tag:kiBKwaY7SnEPhBAZjzpSjQ==,type:str]
data:
    #ENC[AES256_GCM,data:X2lMahFeOrM9zwSg+EHC,iv:nwso7G5jOATmHeBngRK817RPZlAsK/iKF7nw9mBFuGo=,tag:NeLsl/RICBdED48e5TVHsg==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:9yCzuAOI+NA=,iv:21Lk1Bl6PoVbxOK8VGvw195Tm7k2MS/AxFeaf+N+ZWk=,tag:sbgV7XbF3AF+ytMedHXBCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1stnm85pm2s7542u7s52hek2jswy7gscr92y42ppgfefrtklfef9q5szym7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUHpDMWpaNHFlMnRJVmVD
            SGhJUHh2M3FMY09JTnBoajJoNUExWEtXc2kwCnVQaG5WTnpleWtNcHF6eU9zQWlT
            U0RaaFMwMk1iWXBZL3ZuZmRWQXNwZlEKLS0tIGZROXN5cGVJd0E0TkhZNmhqUDUr
            VnZlVDFkM0Z0V0dRaERrMzEzMEtrbncKwTMqdNxT41D7+nYrTJTqQhzJSpGR3O+m
            3gZPxkBJowrO2f3TRDMFfp/4rcyupjCu6D47qApAuX7qsC7yGliskQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-12T17:49:57Z"
    mac: ENC[AES256_GCM,data:1w+PG2dojY8zX6RfRLLG1a0YWABtvdkaTG17/L3e2msiWyRg1OIUBAzRdZtMguoleshOqsflzlz0rmxl/v0QQI3w3bRPXBkY8YqSuiy+Z1x+bgujQ+Jo8MNRV//YPo56lFgcOuemg4xsFrotmjN6vZMfdhQ44o/6PxrD7UBJjvk=,iv:rAmKQWoHnHgw9WO2OfAd1XxrzNRBf+LyDxzy2YMnFF4=,tag:vpRsEOh0Z4GugbP0IxXQVQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
