apiVersion: v1
kind: Service
metadata:
  name: main-svc
spec:
  type: ClusterIP
  selector:
    app: main-app
  ports:
    - name: http
      protocol: TCP
      port: 2345
      targetPort: 3001
    - name: pingpongport
      port: 2346
      protocol: TCP
      targetPort: 3000