apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-password
  namespace: project-namespace
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBss4FWc2HnKvAF/tE3fOJlkekbXIYpuESrUfejY5fBFghocsSnqnB8ln7exmsiAzZCKOt7p4hMm7ce7H8CsZH3vjoZh4GJJFfRvsbgUs0UdCADo4162OQg8uAaCoS2UBEh1qIQ2wKWiVJLOUIgFZhzzA15OtyjWpiFGk/18wbzdjSdai4aeng4YuyTjCFrFrkvDk18xx2JqDN6bot+twjeOfocR12NNwRMF67okyxZhkw8ukupaxdmAEdvwRtDIonayibTtSfV/Ga62CqizOFzcql9Ej2iSedlGSwG9Z+JWwgobotGLmvDMZHHrDdnji25OeDY3j8Ev+poBgzNv2yGcqnyBvpmAPHl7/QciAjdVlqUU1XAW+WF5wp7ThVibszvSpuhwbo9fgVJfBuhadVro5m/tH1KpD2YDj/url9C5kG6UDx3ZRbHeZ4VeLkoGHC2D3sB2cGAULSGzUQr/58FVZCA134BxO4waION8fmNK5t/pUMjj++FDAeZeUvuJBpisfN7uvlziOElbC0i7iFsV2LiK7nFBCh8LzYg0tzXtnVdUSUrIZKm8MYFFauLp1AQg44zzFRUOSEN6w2cf72sH0ceqTw+8La9oYzBzEuwwHnuw0KSIq5Zlv9PtU5EqAXOUqwKsCFN0lLBunq83dmblDW+u54eBTkP5IDmfR/6c2I8LN2rYFoSorkj0aKm89k20Y0c
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: db-password
      namespace: project-namespace

